vich_uploader:
  db_driver: orm

  mappings:
    projects_image:
      uri_prefix: /images/projects
      upload_destination: "%kernel.project_dir%/public/images/projects"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
